### ISSUE TITLE
Compilation fails with OpenDLV.core v0.8.0

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv#124]
@fgiaimo After activating the DBC changes in OpenDLV.core (v.0.8.0), OpenDLV (branch: 2016Q4.refactoring.dbc) does not compile and resulting with the following error:

Could you please check and fix this so that we can proceed merging the changes to the higher levels?

/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp: In member function 'virtual void opendlv::knowledge::gcdc16::rule::intersection::Intersection::nextContainer(odcore::data::Container&)':
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp:187:71: error: 'opendlv::proxy::reverefh16::Propulsion' has not been declared
   } else if (a_container.getDataType() == opendlv::proxy::reverefh16::Propulsion::ID()) {
                                                                       ^
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp:188:43: error: 'Propulsion' is not a member of 'opendlv::proxy::reverefh16'
     auto propulsion = a_container.getData<opendlv::proxy::reverefh16::Propulsion>();
                                           ^
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp:188:43: error: 'Propulsion' is not a member of 'opendlv::proxy::reverefh16'
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp:188:83: error: no matching function for call to 'odcore::data::Container::getData()'
     auto propulsion = a_container.getData<opendlv::proxy::reverefh16::Propulsion>();
                                                                                   ^
In file included from /opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp:26:0:
/opt/od4/include/opendavinci/odcore/data/Container.h:104:26: note: candidate: template<class T> T odcore::data::Container::getData()
                 inline T getData() {
                          ^
/opt/od4/include/opendavinci/odcore/data/Container.h:104:26: note:   template argument deduction/substitution failed:
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/intersection/intersection.cpp:188:83: error: template argument 1 is invalid
     auto propulsion = a_container.getData<opendlv::proxy::reverefh16::Propulsion>();
                                                                                   ^
application/knowledge/CMakeFiles/opendlv-system-application-knowledgelib-static.dir/build.make:110: recipe for target 'application/knowledge/CMakeFiles/opendlv-system-application-knowledgelib-static.dir/src/gcdc16/rule/intersection/intersection.cpp.o' failed
make[2]: *** [application/knowledge/CMakeFiles/opendlv-system-application-knowledgelib-static.dir/src/gcdc16/rule/intersection/intersection.cpp.o] Error 1
CMakeFiles/Makefile2:757: recipe for target 'application/knowledge/CMakeFiles/opendlv-system-application-knowledgelib-static.dir/all' failed
make[1]: *** [application/knowledge/CMakeFiles/opendlv-system-application-knowledgelib-static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 34%] Building CXX object application/action/CMakeFiles/opendlv-system-application-action-act.dir/src/act/main.cpp.o
[ 34%] Building CXX object application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/src/proprioception/balance/balance.cpp.o
[ 35%] Linking CXX executable opendlv-system-application-action-act
In file included from /opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:35:0:
/opt/opendlv.sources/code/system/application/sensation/include/geolocation/geolocation.hpp:85:31: error: 'Propulsion' in namespace 'opendlv::proxy::reverefh16' does not name a type
   opendlv::proxy::reverefh16::Propulsion m_propulsionReading;
                               ^
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp: In constructor 'opendlv::sensation::geolocation::Geolocation::Geolocation(const int32_t&, char**)':
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:57:7: error: class 'opendlv::sensation::geolocation::Geolocation' does not have any field named 'm_propulsionReading'
     , m_propulsionReading()
       ^
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp: In member function 'virtual void opendlv::sensation::geolocation::Geolocation::nextContainer(odcore::data::Container&)':
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:98:62: error: 'opendlv::proxy::reverefh16::Propulsion' has not been declared
   } else if(a_c.getDataType() == opendlv::proxy::reverefh16::Propulsion::ID()) {
                                                              ^
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:99:5: error: 'm_propulsionReading' was not declared in this scope
     m_propulsionReading = a_c.getData<opendlv::proxy::reverefh16::Propulsion>();
     ^
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:99:39: error: 'Propulsion' is not a member of 'opendlv::proxy::reverefh16'
     m_propulsionReading = a_c.getData<opendlv::proxy::reverefh16::Propulsion>();
                                       ^
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:99:39: error: 'Propulsion' is not a member of 'opendlv::proxy::reverefh16'
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:99:79: error: no matching function for call to 'odcore::data::Container::getData()'
     m_propulsionReading = a_c.getData<opendlv::proxy::reverefh16::Propulsion>();
                                                                               ^
In file included from /opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:29:0:
/opt/od4/include/opendavinci/odcore/data/Container.h:104:26: note: candidate: template<class T> T odcore::data::Container::getData()
                 inline T getData() {
                          ^
/opt/od4/include/opendavinci/odcore/data/Container.h:104:26: note:   template argument deduction/substitution failed:
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:99:79: error: template argument 1 is invalid
     m_propulsionReading = a_c.getData<opendlv::proxy::reverefh16::Propulsion>();
                                                                               ^
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp: In member function 'virtual odcore::data::dmcp::ModuleExitCodeMessage::ModuleExitCode opendlv::sensation::geolocation::Geolocation::body()':
/opt/opendlv.sources/code/system/application/sensation/src/geolocation/geolocation.cpp:191:40: error: 'm_propulsionReading' was not declared in this scope
     float const v = static_cast<float>(m_propulsionReading.getPropulsionShaftVehicleSpeed()/3.6);
                                        ^
application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/build.make:158: recipe for target 'application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/src/geolocation/geolocation.cpp.o' failed
make[2]: *** [application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/src/geolocation/geolocation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 35%] Built target opendlv-system-application-action-act
In file included from /opt/opendlv.sources/code/system/application/sensation/src/geolocation/main.cpp:20:0:
/opt/opendlv.sources/code/system/application/sensation/include/geolocation/geolocation.hpp:85:31: error: 'Propulsion' in namespace 'opendlv::proxy::reverefh16' does not name a type
   opendlv::proxy::reverefh16::Propulsion m_propulsionReading;
                               ^
application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/build.make:182: recipe for target 'application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/src/geolocation/main.cpp.o' failed
make[2]: *** [application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/src/geolocation/main.cpp.o] Error 1
CMakeFiles/Makefile2:1343: recipe for target 'application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/all' failed
make[1]: *** [application/sensation/CMakeFiles/opendlv-system-application-sensationlib-static.dir/all] Error 2

**Comment by fgiaimo** [comment]
the "Propulsion" message has been renamed "VehicleSpeed". I was pretty sure to have renamed all the occurrences of the modified names.

**Comment by fgiaimo** [comment]
I fixed those two files

**Comment by chrberger** [comment]
Thanks; merged into my branch and triggered rebuilding.

**Comment by chrberger** [comment]
Still failing:

/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp: In member function 'void opendlv::knowledge::gcdc16::rule::platoon::Platoon::receivedContainerMergeScenario(odcore::data::Container&)':
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp:231:64: error: 'opendlv::proxy::reverefh16::Propulsion' has not been declared
   if (a_container.getDataType() == opendlv::proxy::reverefh16::Propulsion::ID()) {
                                                                ^
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp:232:43: error: 'Propulsion' is not a member of 'opendlv::proxy::reverefh16'
     auto propulsion = a_container.getData<opendlv::proxy::reverefh16::Propulsion>();
                                           ^
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp:232:43: error: 'Propulsion' is not a member of 'opendlv::proxy::reverefh16'
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp:232:83: error: no matching function for call to 'odcore::data::Container::getData()'
     auto propulsion = a_container.getData<opendlv::proxy::reverefh16::Propulsion>();
                                                                                   ^
In file included from /opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp:25:0:
/opt/od4/include/opendavinci/odcore/data/Container.h:104:26: note: candidate: template<class T> T odcore::data::Container::getData()
                 inline T getData() {
                          ^
/opt/od4/include/opendavinci/odcore/data/Container.h:104:26: note:   template argument deduction/substitution failed:
/opt/opendlv.sources/code/system/application/knowledge/src/gcdc16/rule/platoon/platoon.cpp:232:83: error: template argument 1 is invalid
     auto propulsion = a_container.getData<opendlv::proxy::reverefh16::Propulsion>();

**Comment by fgiaimo** [comment]
fixed this one too
